name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened,synchronize,ready_for_review,edited]

# Cancel previous workflow run groups that have not completed.
concurrency:
  # Group workflow runs by workflow name, along with the head branch ref of the pull request
  # or otherwise the branch or tag ref.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        uses: php-actions/composer@v6

      - name: PHP_CodeSniffer
        run: |
          cd ${GITHUB_WORKSPACE}
          ./vendor/bin/phpcs --standard=./phpcs.xml
