name: Lint

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened,synchronize,ready_for_review,edited]

# Cancel previous workflow run groups that have not completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Install Composer dependencies
        uses: php-actions/composer@v6

      - name: PHP_CodeSniffer
        run: |
          cd ${GITHUB_WORKSPACE}
          ./vendor/bin/phpcs --standard=./phpcs.xml
