name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create releasee zip
        run: |
            make clean
            make release

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1.18.0
        with:
          artifacts: "chriswiegman-plugin.${{ env.RELEASE_VERSION }}.zip"
          bodyFile: ".changes/${{ env.RELEASE_VERSION }}.md"